version: '3.8'

services:
  fix-kvm:
    image: zerosuxx/alpine
    volumes:
      - "/dev/kvm:/dev/kvm"
    command: "chgrp 108 /dev/kvm"

  app:
    image: zerosuxx/android-emulator
    build: .
    devices:
      - "/dev/kvm:/dev/kvm"
    volumes:
      - ".:/app"
    restart: on-failure
